Bump PyYAML version 5.4 -> 5.4.1
With `PyYAML==5.4` in `requirements.txt`, `docker build app` would fail
with an exception:

    ERROR: Could not find a version that satisfies the requirement
        PyYAML==5.4 (from versions: 3.10, 3.11, 3.12, 3.13b1, 3.13rc1,
        3.13, 4.2b1, 4.2b2, 4.2b4, 5.1b1, 5.1b3, 5.1b5, 5.1, 5.1.1,
        5.1.2, 5.2b1, 5.2, 5.3b1, 5.3, 5.3.1, 5.4b1, 5.4b2, 5.4, 5.4.1,
        6.0b1, 6.0, 6.0.1)
    ERROR: No matching distribution found for PyYAML==5.4

Upgrading to 5.4.1 fixes it.